trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    exclude:
    - 'website/*'
    - '*.md'
pr:
  paths:
    exclude:
    - 'website/*'
    - '*.md'

jobs:
#- job: 'Test'
#  variables:
#    NOTEBOOK_KERNEL: "thinc-notebook-tests"
#  strategy:
#    matrix:
#      Python36Linux:
#        imageName: 'ubuntu-16.04'
#        python.version: '3.6'
#      Python36Windows:
#        imageName: 'vs2017-win2016'
#        python.version: '3.6'
#      Python36Mac:
#        imageName: 'macos-10.15'
#        python.version: '3.6'
#      Python38Linux:
#        imageName: 'ubuntu-16.04'
#        python.version: '3.8'
#      Python38Windows:
#        imageName: 'vs2017-win2016'
#        python.version: '3.8'
#      Python38Mac:
#        imageName: 'macos-10.15'
#        python.version: '3.8'
#      Python39Linux:
#        imageName: 'ubuntu-16.04'
#        python.version: '3.9'
#      Python39Windows:
#        imageName: 'vs2017-win2016'
#        python.version: '3.9'
#      Python39Mac:
#        imageName: 'macos-10.15'
#        python.version: '3.9'
#    maxParallel: 4
#  pool:
#    vmImage: $(imageName)
#  steps:
#  - template: .azure/steps.yml
#    parameters:
#      python_version: '$(python.version)'
#      architecture: 'x64'
#      gpu: false

- job: 'TestGPU'
  variables:
    NOTEBOOK_KERNEL: "thinc-notebook-tests"
  strategy:
    matrix:
      Python38LinuxX64_GPU:
        python.version: '3.8'
  pool:
    name: "LinuxX64_GPU"
  steps:
  - template: .azure/steps.yml
    parameters:
      python_version: '$(python.version)'
      architecture: 'x64'
      gpu: true
