[build-system]
requires = [
    "setuptools",
    "cython>=0.25",
    "numpy>=1.7.0",
    "murmurhash>=0.28.0,<1.1.0",
    "cymem>=2.0.2,<2.1.0",
    "preshed>=1.0.1,<3.1.0",
]
build-backend = "setuptools.build_meta"
